apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  # namespace: cert-manager
spec:
  vault:
    path: pki_int/sign/local
    auth:
      kubernetes:
        role: certs-creator
        mountPath: /v1/auth/kubernetes
        secretRef:
          key: token
