apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      extraEnvironmentVars:
        VAULT_SEAL_TYPE: awskms
      # extraSecretEnvironmentVars:
      #   - envName: AWS_ACCESS_KEY_ID
      #     secretName: eks-creds
      #     secretKey: AWS_ACCESS_KEY_ID
      #   - envName: AWS_SECRET_ACCESS_KEY
      #     secretName: eks-creds
      #     secretKey: AWS_SECRET_ACCESS_KEY
      #   - envName: AWS_REGION
      #     secretName: eks-creds
      #     secretKey: VAULT_AWS_REGION
      #   - envName: VAULT_AWSKMS_SEAL_KEY_ID
      #     secretName: eks-creds
      #     secretKey: VAULT_AWSKMS_SEAL_KEY_ID

      extraEnvironmentVars:
        VAULT_AWSKMS_SEAL_KEY_ID: d6e7a81c-0efb-4f0f-b5f5-1d3643d6efd1
        AWS_REGION: eu-west-2
        AWS_ACCESS_KEY_ID: "AKIAXFOLVZORMZHJY4EF"
        AWS_SECRET_ACCESS_KEY: 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
          
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::492737776546:role/rohit-vault
    ui:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: vault.rohit.local
