apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      extraEnvironmentVars:
        VAULT_AUTO_UNSEAL_KMS_ID: d6e7a81c-0efb-4f0f-b5f5-1d3643d6efd1
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::492737776546:role/rohit-vault
    ui:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: vault.rohit.local
